# PyInstaller spec for AgeniusNote Lite (Windows + macOS).
#
# Build:
#     cd apps/voice-notes-desktop
#     pyinstaller packaging/ageniusnote_lite.spec --noconfirm --clean
#
# Output:
#     Windows : dist/AgeniusNoteLite/AgeniusNoteLite.exe   (one-folder)
#     macOS   : dist/AgeniusNoteLite.app                   (.app bundle)
#
# We deliberately use --onedir (not --onefile) because faster-whisper +
# CTranslate2 + onnxruntime ship hundreds of MB of native binaries, and
# --onefile unpacks them to a temp dir on every launch (slow start, AV scans).
from __future__ import annotations

import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

IS_WIN = sys.platform == "win32"
IS_MAC = sys.platform == "darwin"

here = Path.cwd()
app_dir = here  # caller should `cd apps/voice-notes-desktop` first
entry = str(app_dir / "voice_notes_lite.py")

# Single source of truth for the version. Bundle Info.plist reads this.
try:
    VERSION = (app_dir / "packaging" / "VERSION").read_text().strip()
except FileNotFoundError:
    VERSION = "0.0.0"

icon_path = str(app_dir / "assets" / ("icon.icns" if IS_MAC else "icon.ico"))


def _generate_win_version_file(version_str: str, target: Path) -> str:
    """Write a PyInstaller VSVersionInfo file populated from VERSION.

    The bundled AgeniusNoteLite.exe gets these strings in its Windows file
    properties (Details tab). AV engines and SmartScreen treat exes with
    blank version resources as more suspicious; populating them is the
    cheapest trust signal available short of code-signing.
    """
    parts = version_str.split(".")
    while len(parts) < 4:
        parts.append("0")
    try:
        nums = tuple(int(p) for p in parts[:4])
    except ValueError:
        nums = (0, 0, 0, 0)
    content = (
        "# Auto-generated by ageniusnote_lite.spec. Do not edit by hand.\n"
        "VSVersionInfo(\n"
        "  ffi=FixedFileInfo(\n"
        f"    filevers={nums},\n"
        f"    prodvers={nums},\n"
        "    mask=0x3f,\n"
        "    flags=0x0,\n"
        "    OS=0x40004,\n"
        "    fileType=0x1,\n"
        "    subtype=0x0,\n"
        "    date=(0, 0),\n"
        "  ),\n"
        "  kids=[\n"
        "    StringFileInfo([\n"
        "      StringTable(\n"
        "        '040904B0',\n"
        "        [\n"
        "          StringStruct('CompanyName', 'Agenius AI Labs'),\n"
        "          StringStruct('FileDescription', "
        "'AgeniusNote Lite - local voice-to-text dictation'),\n"
        f"          StringStruct('FileVersion', '{version_str}'),\n"
        "          StringStruct('InternalName', 'AgeniusNoteLite'),\n"
        "          StringStruct('LegalCopyright', "
        "'Copyright (c) Agenius AI Labs. MIT licensed.'),\n"
        "          StringStruct('OriginalFilename', 'AgeniusNoteLite.exe'),\n"
        "          StringStruct('ProductName', 'AgeniusNote Lite'),\n"
        f"          StringStruct('ProductVersion', '{version_str}'),\n"
        "        ],\n"
        "      ),\n"
        "    ]),\n"
        "    VarFileInfo([VarStruct('Translation', [1033, 1200])]),\n"
        "  ],\n"
        ")\n"
    )
    target.write_text(content, encoding="utf-8")
    return str(target)


version_file = None
if IS_WIN:
    version_file = _generate_win_version_file(
        VERSION, app_dir / "packaging" / "_version_info.txt"
    )

datas = [
    (str(app_dir / "assets"), "assets"),
    # Ship VERSION inside the bundle so APP_VERSION reads it at runtime
    # (no more hardcoded version-label drift).
    (str(app_dir / "packaging" / "VERSION"), "packaging"),
    # Required by faster-whisper VAD at runtime.
    *collect_data_files("faster_whisper", includes=["assets/*.onnx"]),
]

hiddenimports = []
if IS_WIN:
    hiddenimports += [
        "pynput.keyboard._win32",
        "pynput.mouse._win32",
    ]
if IS_MAC:
    hiddenimports += [
        "pynput.keyboard._darwin",
        "pynput.mouse._darwin",
    ]

a = Analysis(
    [entry],
    pathex=[str(app_dir)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Faster-whisper uses CTranslate2, not PyTorch. Drop ~4.2 GB of torch.
        "torch",
        "torchvision",
        "torchaudio",
        # Transformers pulls torch back in and isn't needed (faster-whisper
        # uses `tokenizers` directly with a bundled vocab).
        "transformers",
        # Numba/llvmlite (~100 MB) come in transitively but aren't used.
        "numba",
        "llvmlite",
        # We don't use openwakeword in lite mode -> drops sklearn + tflite.
        "openwakeword",
        "sklearn",
        "scikit_learn",
        # Note: PyAV (~74 MB) IS required by faster-whisper for audio decoding,
        # even when feeding it a WAV file path. Do not exclude.
        # General junk pulled in by transitive deps.
        "tkinter",
        "matplotlib",
        "pytest",
        "IPython",
        "jupyter",
        "notebook",
        "pandas",
        "lxml",
        "cryptography",  # only used for HF auth; not needed for local models
        "hf_xet",        # huggingface accelerated download backend
        "pyarrow",
        "scipy",         # sklearn / openwakeword dep; not used elsewhere
        "websockets",
        # NOTE: do NOT exclude "yaml" — faster-whisper / ctranslate2 import it
        # at transcription time. Excluding it broke v1.0.0 installer with
        # "No module named 'yaml'" on first transcription.
        "zstandard",
        "yarl",
        "aiohttp",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="AgeniusNoteLite",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_path,
    version=version_file,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="AgeniusNoteLite",
)

if IS_MAC:
    app = BUNDLE(
        coll,
        name="AgeniusNote Lite.app",
        icon=icon_path,
        bundle_identifier="com.ageniusailabs.ageniusnote-lite",
        info_plist={
            "CFBundleName": "AgeniusNote Lite",
            "CFBundleDisplayName": "AgeniusNote Lite",
            "CFBundleShortVersionString": VERSION,
            "CFBundleVersion": VERSION,
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "11.0",
            # Required permission prompts on first run:
            "NSMicrophoneUsageDescription":
                "AgeniusNote Lite uses the microphone to transcribe your voice "
                "into text locally on your machine.",
            "NSAppleEventsUsageDescription":
                "AgeniusNote Lite uses Apple Events to detect the focused app "
                "so it can paste your dictation into the right window.",
        },
    )
